import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Player from "@/components/Player";

import AuthProvider from "@/app/providers";

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
    display: "swap",
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={montserrat.className}>
        <body className="font-sans antialiased">
        <AuthProvider>
            <div className="min-h-screen bg-black text-white">
                <Header />
                {children}
                <Footer />
                <Player />
            </div>
        </AuthProvider>
        </body>
        </html>
    );
}