import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="min-h-screen bg-gray-900 text-white">
        {/* Header */}
        <header className="bg-black border-b border-gray-800 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-6">
            <div className="text-2xl font-bold text-white">🎵</div>
            <nav className="hidden md:flex space-x-6">
              <a href="#" className="hover:text-gray-300 transition">Home</a>
              <a href="#" className="hover:text-gray-300 transition">Feed</a>
              <a href="#" className="hover:text-gray-300 transition">Library</a>
            </nav>
          </div>

          <div className="flex items-center space-x-4">
            <div className="relative w-72">
              <input
                  type="text"
                  placeholder="What would you like to listen?"
                  className="w-full bg-gray-800 text-white rounded-lg pl-10 pr-4 py-2 focus:outline-none focus:ring-2 focus:ring-purple-500"
              />
              <svg className="absolute left-3 top-2.5 h-5 w-5 text-gray-400" fill="none" stroke="currentColor"
                   viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                      d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
              </svg>
            </div>
            <button className="text-sm text-purple-500 hover:text-purple-400 transition">Try Artis Pro</button>
            <button className="text-sm hover:text-gray-300 transition">For Artists</button>
            <button className="text-sm hover:text-gray-300 transition">Upload</button>
            <button className="w-8 h-8 rounded-full bg-gray-700 flex items-center justify-center">
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 2a8 8 0 100 16 8 8 0 000-16zM8 10a2 2 0 114 0 2 2 0 01-4 0z"/>
              </svg>
            </button>
            <button className="w-8 h-8 rounded-full bg-gray-700 flex items-center justify-center">
              <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                <path d="M10 2a8 8 0 100 16 8 8 0 000-16zm0 14a6 6 0 110-12 6 6 0 010 12z"/>
              </svg>
            </button>
          </div>
        </header>

        {children}

        {/* Footer */}
        <footer className="bg-gray-800 border-t border-gray-700 px-6 py-8">
          <div className="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-5 gap-8">
            <div>
              <h3 className="font-semibold mb-4">Company</h3>
              <ul className="space-y-2 text-sm text-gray-400">
                <li><a href="#" className="hover:text-white transition">About</a></li>
                <li><a href="#" className="hover:text-white transition">For the Record</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Communities</h3>
              <ul className="space-y-2 text-sm text-gray-400">
                <li><a href="#" className="hover:text-white transition">For Artists</a></li>
                <li><a href="#" className="hover:text-white transition">Advertising</a></li>
                <li><a href="#" className="hover:text-white transition">Investors</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Useful links</h3>
              <ul className="space-y-2 text-sm text-gray-400">
                <li><a href="#" className="hover:text-white transition">Support</a></li>
                <li><a href="#" className="hover:text-white transition">Popular by Country</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Wave Plans</h3>
              <ul className="space-y-2 text-sm text-gray-400">
                <li><a href="#" className="hover:text-white transition">Artists</a></li>
                <li><a href="#" className="hover:text-white transition">Artists Pro</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Go Mobile</h3>
              <div className="flex space-x-4">
                <a href="#" className="flex items-center">
                  <img src="https://play.google.com/intl/en_us/badges/images/generic/google_play_badge_web_generic.png"
                       alt="Google Play" className="h-8"/>
                </a>
                <a href="#" className="flex items-center">
                  <img
                      src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Apple_App_Store.svg/1200px-Apple_App_Store.svg.png"
                      alt="App Store" className="h-8"/>
                </a>
              </div>
            </div>
          </div>
          <div className="mt-8 pt-6 border-t border-gray-700 text-center text-xs text-gray-500">
            <p>Legal • Cookies • About Ads • Accessibility • Safety & Privacy Center • Privacy Policy</p>
            <p className="mt-2">© 2025 All rights reserved.</p>
          </div>
        </footer>
      </div>
      </body>
      </html>
  );
}

