import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Player from "@/components/Player";

import AuthProvider from "@/app/providers";

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
    display: "swap",
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Wavve",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={montserrat.className}>
        <body className="font-sans antialiased">
        <AuthProvider>
            <div className="relative min-h-screen bg-black text-white overflow-hidden">
                <div
                    className="absolute inset-0 bg-[url('/bgnav.png')] bg-cover bg-center bg-no-repeat"
                >
                    <div className="absolute inset-0 bg-gradient-to-b from-black/80 via-black/60 to-transparent" />
                </div>

                <div className="relative z-10">
                    <Header />
                    {children}
                    <Footer />
                    <Player />
                </div>
            </div>
        </AuthProvider>
        </body>
        </html>
    );
}